/**
 * 議 Three directions for the art, drawn rather than described.
 *
 * Bruno: *"tenta melhorar a arte, não diretamente no jogo mas faz umas propostas
 * visuais de A a C."* So nothing here is wired into the game. Every drawing on this
 * page is generated by this file, from the game's own tables and its own icons, so a
 * proposal can be looked at beside the thing it would replace.
 *
 * The three are not three styles to pick between on taste. They are three *amounts*:
 *
 *   甲 A 印 The Seal      a frame around what is already there. Hours, no new assets.
 *   乙 B 幕 The Scene     every screen becomes a place that reads the save. Days.
 *   丙 C 繪 The Painted   real pictures for the 45 named creatures. Weeks, and money
 *                         or a licence, and the only one that raises the ceiling.
 *
 * Run with `npm run artprops`. It writes art-proposals.html.
 */
import { writeFileSync } from 'node:fs';
import { BEASTS, commonsOf, wardenOf } from '../src/data/bestiary.ts';
import { realm as realmOf } from '../src/data/realms.ts';
import { GEAR } from '../src/data/gear.ts';
import { ICONS } from '../src/art/icons.generated.ts';
import { icon } from '../src/art/icon.ts';
import { mix, portrait } from '../src/art/aura.ts';
import { arenaScene } from '../src/art/scene.ts';
import { PLATE_CSS, liftArt, writePlates } from './lift.ts';

/* ── 甲 A · 印 The seal ──────────────────────────────────────────────────────
   The warden seals already prove it: the same borrowed silhouette inside a drawn
   frame stops reading as clip art. This is that frame, given a rank and a realm, so
   it can go on every beast, every card and every piece of gear in the game. */

/**
 * 印 A sealed creature: the icon, a ring in its realm's colour, and a rank's worth of
 * ceremony around it. Nothing here is a new drawing. It is all frame.
 */
function sealed(iconName: string, colour: string, tier: number, size = 92): string {
  const body = ICONS[iconName] ?? '';
  const uid = `s${iconName}${tier}`;
  const glow = mix(colour, '#05060F', 0.55);
  // 階 The ceremony grows with the tier: a plain ring, then a dashed orbit, then
  // spokes, then a full corona. The same idea 器 the gear frames already use.
  const orbit = tier >= 1 ? `<circle cx="50" cy="50" r="43" fill="none" stroke="${colour}"
      stroke-opacity=".34" stroke-width=".8" stroke-dasharray="3 5"/>` : '';
  const spokes = tier >= 2 ? Array.from({ length: 12 }, (_, i) => {
    const a = (i / 12) * Math.PI * 2;
    const r0 = 47; const r1 = i % 2 ? 50 : 52;
    return `<line x1="${(50 + Math.cos(a) * r0).toFixed(1)}" y1="${(50 + Math.sin(a) * r0).toFixed(1)}"
      x2="${(50 + Math.cos(a) * r1).toFixed(1)}" y2="${(50 + Math.sin(a) * r1).toFixed(1)}"
      stroke="${colour}" stroke-opacity="${i % 2 ? 0.3 : 0.6}" stroke-width="${i % 2 ? 0.7 : 1.1}"/>`;
  }).join('') : '';
  const corona = tier >= 3 ? `<circle cx="50" cy="50" r="49" fill="none" stroke="${colour}"
      stroke-opacity=".7" stroke-width="1.4"/>` : '';
  return `<svg viewBox="-4 -4 108 108" width="${size}" height="${size}" aria-hidden="true">
    <defs><radialGradient id="g${uid}"><stop offset=".3" stop-color="${colour}" stop-opacity=".26"/>
      <stop offset="1" stop-color="${colour}" stop-opacity="0"/></radialGradient></defs>
    <circle cx="50" cy="50" r="50" fill="url(#g${uid})"/>
    <circle cx="50" cy="50" r="38" fill="${glow}"/>
    <circle cx="50" cy="50" r="47" fill="none" stroke="${colour}" stroke-opacity=".5" stroke-width="1.2"/>
    ${orbit}${spokes}${corona}
    <g transform="translate(26 26) scale(0.09375)" fill="${colour}">${body}</g>
  </svg>`;
}

/** 對 The fight as it is: a drawn cultivator against a flat symbol. */
const arenaNow = (realm: number, beastIcon: string, colour: string) => `
  <div class="arena">
    <span class="bg">${arenaScene(realm)}</span>
    <span class="who">${portrait({ realm: Math.max(1, realm - 1), focus: true })}</span>
    <span class="mid cjk">擊</span>
    <span class="foe flat" style="color:${colour}">${icon(beastIcon, 86)}</span>
  </div>`;

/** 對 And the same fight with the beast given what the cultivator already has. */
const arenaSealed = (realm: number, beastIcon: string, colour: string) => `
  <div class="arena">
    <span class="bg">${arenaScene(realm)}</span>
    <span class="who">${portrait({ realm: Math.max(1, realm - 1), focus: true })}</span>
    <span class="mid cjk">擊</span>
    <span class="foe">${sealed(beastIcon, colour, 3, 104)}</span>
  </div>`;

/* ── 乙 B · 幕 The scene ─────────────────────────────────────────────────────
   Six drawings in this game read the save. This asks what the other screens would
   look like if they did too. */

/**
 * 帶 A band of the realm's own sky, sat behind a list.
 *
 * It is the arena's own scenery, cropped to a strip: the same function, the same
 * seeded hills, drawn once at the top of a screen so 狩 the hunt happens somewhere.
 */
function band(realm: number, height = 86): string {
  const r = realmOf(realm);
  return `<svg viewBox="0 0 320 ${height}" preserveAspectRatio="none" width="100%" height="${height}" aria-hidden="true">
    <defs>
      <linearGradient id="b${realm}" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="${mix(r.colour, '#05060F', 0.72)}"/>
        <stop offset="1" stop-color="#080A18"/>
      </linearGradient>
    </defs>
    <rect width="320" height="${height}" fill="url(#b${realm})"/>
    ${Array.from({ length: 18 }, (_, i) => {
      const x = (i * 97 + realm * 31) % 320;
      const y = 6 + ((i * 53 + realm * 17) % (height - 30));
      return `<circle cx="${x}" cy="${y}" r="${(i % 3) * 0.5 + 0.7}" fill="${r.colour}" opacity="${0.1 + (i % 4) * 0.07}"/>`;
    }).join('')}
    <polygon points="0,${height} 60,${height - 34} 120,${height - 12} 190,${height - 40} 250,${height - 16} 320,${height - 30} 320,${height}"
      fill="${mix(r.colour, '#05060F', 0.86)}"/>
    <rect y="${height - 2}" width="320" height="2" fill="${r.colour}" opacity=".4"/>
  </svg>`;
}

/** 流 The bar, with the qi actually moving in it. The animation is one CSS line. */
const qiBar = (colour: string) => `
  <span class="bar"><i style="--c:${colour};width:62%"></i></span>`;

/* ── 丙 C · 繪 The painted game ──────────────────────────────────────────────
   45 named creatures with real pictures. This page cannot draw those; what it can do
   is show the *shape* of the change, so the cost is argued about honestly. */

/**
 * 繪 A stand-in for a painted card: an ink wash, a horizon, and the silhouette held
 * inside it. It is a mock of a treatment, not a mock of a picture. The real version is
 * a 512 by 512 painting, and the point of this block is the frame it would sit in.
 */
function painted(iconName: string, colour: string, name: string, han: string): string {
  const body = ICONS[iconName] ?? '';
  const uid = `p${iconName}`;
  return `<div class="paint" style="--hue:${colour}">
    <svg viewBox="0 0 240 150" width="100%" height="150" aria-hidden="true">
      <defs>
        <linearGradient id="sky${uid}" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="${mix(colour, '#05060F', 0.62)}"/>
          <stop offset="1" stop-color="${mix(colour, '#05060F', 0.92)}"/>
        </linearGradient>
        <filter id="ink${uid}" x="-20%" y="-20%" width="140%" height="140%">
          <feTurbulence type="fractalNoise" baseFrequency=".02 .05" numOctaves="3" seed="7"/>
          <feDisplacementMap in="SourceGraphic" scale="6"/>
        </filter>
        <radialGradient id="hal${uid}"><stop offset=".2" stop-color="${colour}" stop-opacity=".4"/>
          <stop offset="1" stop-color="${colour}" stop-opacity="0"/></radialGradient>
      </defs>
      <rect width="240" height="150" fill="url(#sky${uid})"/>
      <ellipse cx="120" cy="96" rx="78" ry="46" fill="url(#hal${uid})"/>
      <path d="M0 132 Q40 108 78 124 T160 116 T240 128 L240 150 L0 150 Z"
        fill="${mix(colour, '#05060F', 0.95)}" filter="url(#ink${uid})" opacity=".9"/>
      <g transform="translate(78 32) scale(0.164)" fill="${mix(colour, '#FFFFFF', 0.35)}"
         filter="url(#ink${uid})">${body}</g>
    </svg>
    <div class="cap"><b class="cjk">${han}</b><i>${name}</i></div>
  </div>`;
}

const pack = (name: string, what: string, licence: string, verdict: string, url: string) => `
  <tr><td><b>${name}</b><i style="display:block">${what}</i></td>
    <td>${licence}</td><td>${verdict}</td>
    <td><a href="${url}">open</a></td></tr>`;

const three = commonsOf(6);
const six = realmOf(6);
const eight = realmOf(8);

const page = `<meta charset="utf-8">
<title>九境 Ninefold · 議 three directions for the art</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600&family=Noto+Serif+SC:wght@400;600&family=Rajdhani:wght@600;700&display=swap">
<style>
  :root { --ground:#080A18; --panel:#111433; --panel2:#0C0F26; --line:#252A5C;
          --cyan:#5FDCFF; --magenta:#FF5FC8; --text:#E7EAFF; --faint:#8289C0;
          --gold:#FFCE6B; color-scheme:dark; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--ground); color:var(--text);
         font:17px/1.65 Archivo, ui-sans-serif, system-ui, sans-serif; }
  .sheet { max-width:900px; margin:0 auto; padding:34px 18px 90px; }
  .cjk { font-family:'Noto Serif SC',serif; }
  h1 { font-family:'Noto Serif SC',serif; font-size:clamp(38px,11vw,56px); font-weight:400;
       color:var(--cyan); line-height:1; margin:0; }
  h2 { font-family:Rajdhani,sans-serif; font-size:26px; margin:0; display:flex; gap:11px;
       align-items:baseline; }
  h2 .h { font-family:'Noto Serif SC',serif; font-weight:400; font-size:30px; color:var(--hue,var(--cyan)); }
  h3 { font-family:Rajdhani,sans-serif; font-size:13px; color:var(--faint); margin:0;
       letter-spacing:.1em; text-transform:uppercase; }
  p { margin:0; }
  .lead { font-size:19px; margin-top:13px; color:var(--faint); }
  .sec { margin-top:40px; border-top:1px solid var(--line); padding-top:22px;
         display:flex; flex-direction:column; gap:14px; }
  .t { color:var(--faint); max-width:64ch; }
  .t b { color:var(--text); font-weight:600; }
  .rule { border-left:3px solid var(--hue,var(--cyan)); background:var(--panel2);
          border-radius:0 10px 10px 0; padding:13px 16px; color:var(--faint); }
  .rule b { color:var(--hue,var(--cyan)); }
  .cost { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:8px; }
  .cost span { background:var(--panel2); border:1px solid var(--line); border-radius:11px;
               padding:10px 13px; }
  .cost b { display:block; font-family:Rajdhani,sans-serif; font-weight:700; font-size:17px;
            color:var(--hue,var(--gold)); }
  .cost i { font-style:normal; font-size:11.5px; color:var(--faint); }
  .two { display:grid; gap:12px; }
  @media(min-width:680px){ .two { grid-template-columns:1fr 1fr; } }
  .box { background:var(--panel2); border:1px solid var(--line); border-radius:13px;
         padding:14px; }
  .box .lab { font-size:11px; letter-spacing:.14em; text-transform:uppercase;
              color:var(--faint); font-family:Archivo,sans-serif; font-weight:600; }
  .row { display:flex; flex-wrap:wrap; gap:14px; align-items:flex-end; margin-top:10px; }
  .row figure { margin:0; text-align:center; }
  .row figcaption { font-size:11px; color:var(--faint); margin-top:5px; }
  .row figcaption b { display:block; font-family:'Noto Serif SC',serif; font-weight:400;
                      font-size:14px; color:var(--hue,var(--cyan)); }
  .flat svg, .row svg { display:block; }
  .arena { position:relative; height:190px; border-radius:12px; overflow:hidden;
           border:1px solid var(--line); display:grid;
           grid-template-columns:1fr 60px 1fr; align-items:center; padding:0 14px; }
  .arena .bg { position:absolute; inset:0; }
  .arena .bg svg { width:100%; height:100%; display:block; }
  .arena .who, .arena .foe { position:relative; display:grid; place-items:center; }
  .arena .who svg { width:104px; height:104px; }
  .arena .mid { position:relative; text-align:center; font-size:20px; color:var(--cyan);
                text-shadow:0 0 14px currentColor; }
  .bar { display:block; height:9px; border-radius:99px; background:rgba(37,42,92,.6);
         overflow:hidden; margin-top:9px; }
  .bar i { display:block; height:100%; border-radius:99px; background:var(--c);
           position:relative; overflow:hidden; }
  .bar i::after { content:''; position:absolute; inset:0;
    background:linear-gradient(90deg,transparent,rgba(255,255,255,.55),transparent);
    transform:translateX(-100%); animation:flow 2.4s linear infinite; }
  @keyframes flow { to { transform:translateX(100%); } }
  .beast { display:flex; align-items:center; gap:12px; padding:10px 12px;
           background:var(--panel); border:1px solid var(--line); border-radius:11px;
           margin-bottom:8px; }
  .beast .s { flex:none; display:grid; place-items:center; width:46px; height:46px; }
  .beast .s svg { display:block; }
  .beast b { font-size:16px; font-weight:400; color:var(--hue); font-family:'Noto Serif SC',serif; }
  .beast i { font-style:normal; font-size:12.5px; color:var(--faint); display:block; }
  .beast em { margin-left:auto; font-style:normal; font-family:Rajdhani,sans-serif;
              font-weight:700; color:var(--cyan); }
  .scr { border:1px solid var(--line); border-radius:13px; overflow:hidden;
         background:var(--panel2); }
  .scr .top { position:relative; }
  .scr .top .ttl { position:absolute; left:14px; bottom:10px; font-family:'Noto Serif SC',serif;
                   font-size:24px; color:var(--text); text-shadow:0 2px 12px #000; }
  .scr .body { padding:12px; }
  .paint { border:1px solid var(--line); border-radius:12px; overflow:hidden; }
  .paint svg { display:block; }
  .paint .cap { padding:9px 12px; }
  .paint .cap b { font-size:17px; font-weight:400; color:var(--hue);
                  font-family:'Noto Serif SC',serif; }
  .paint .cap i { font-style:normal; font-size:12px; color:var(--faint); margin-left:7px; }
  .paints { display:grid; gap:12px; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); }
  table { border-collapse:collapse; width:100%; font-size:14px; }
  th { text-align:left; font-family:Rajdhani,sans-serif; font-size:12px; color:var(--faint);
       letter-spacing:.1em; text-transform:uppercase; padding:0 8px 6px; font-weight:700; }
  td { border-top:1px solid var(--line); padding:8px; color:var(--faint); vertical-align:top; }
  td b { color:var(--text); font-weight:600; }
  td i { font-style:normal; font-size:12px; }
  a { color:var(--cyan); }
  code { font-family:'Roboto Mono',monospace; font-size:13px; color:var(--cyan);
         background:var(--panel2); padding:1px 5px; border-radius:5px; }
  .pill { display:inline-block; font-family:Rajdhani,sans-serif; font-weight:700;
          font-size:12px; letter-spacing:.06em; text-transform:uppercase; padding:3px 9px;
          border-radius:99px; border:1px solid var(--hue); color:var(--hue); }
  pre { background:var(--panel2); border:1px solid var(--line); border-radius:11px;
        padding:14px; overflow-x:auto; font-family:'Roboto Mono',monospace; font-size:12.5px;
        line-height:1.6; color:var(--text); white-space:pre-wrap; }
  ${PLATE_CSS}
</style>

<div class="sheet">
  <header>
    <h1>議</h1>
    <p class="lead"><b style="color:var(--text)">Three directions for the art of 九境.</b>
      Nothing here is wired into the game. Every drawing on this page is generated by
      <code>tools/artprops.ts</code> from the game's own tables and its own icons, so a
      proposal can be looked at beside the thing it would replace.</p>
    <p class="t" style="margin-top:10px">They are not three styles to choose between on
      taste. They are three <b>amounts</b>, and they stack: A is hours and needs nothing
      new, B is days and needs nothing new, C is weeks and needs either money or a
      licence. The honest recommendation is at the bottom.</p>
  </header>

  <section class="sec" style="--hue:var(--cyan)">
    <h2><span class="h">甲</span> A · 印 The Seal</h2>
    <p class="t"><span class="pill">hours</span> <b>Put a frame around what is already
      there.</b> The warden seals already prove this works: the same borrowed silhouette,
      inside a drawn ring in its realm's colour, stops reading as clip art and starts
      reading as a set. Nothing is redrawn. The frame is generated, so it costs no
      download and no licence, and it can carry a rank: a plain ring, then an orbit, then
      spokes, then a corona.</p>
    <div class="two">
      <div class="box"><span class="lab">Now</span>
        <div class="row">${three.map((b) => `<figure>
          <span style="color:${six.colour}">${icon(b.icon, 60)}</span>
          <figcaption><b>${b.han}</b>${b.name}</figcaption></figure>`).join('')}</div>
      </div>
      <div class="box" style="--hue:${six.colour}"><span class="lab">Sealed, by tier</span>
        <div class="row">${three.map((b, i) => `<figure>
          ${sealed(b.icon, six.colour, i + 1, 78)}
          <figcaption><b>${b.han}</b>tier ${i + 1}</figcaption></figure>`).join('')}</div>
      </div>
    </div>
    <h3>對 And the fight, which is the screen it matters most on</h3>
    <div class="two">
      <div class="box"><span class="lab">Now: a drawn cultivator against a flat symbol</span>
        ${arenaNow(6, wardenOf(6).icon, six.colour)}</div>
      <div class="box"><span class="lab">Sealed: both sides drawn the same way</span>
        ${arenaSealed(6, wardenOf(6).icon, six.colour)}</div>
    </div>
    <div class="cost">
      <span><b>0 KB</b><i>generated, nothing downloaded</i></span>
      <span><b>0 licences</b><i>the icons are already shipped</i></span>
      <span><b>${BEASTS.length} + ${GEAR.length}</b><i>things it covers at once</i></span>
      <span><b>1 function</b><i>plus the screens that call it</i></span>
    </div>
    <div class="rule"><b>What it does not fix.</b> Underneath it is still one borrowed
      silhouette per thing, and two beasts of the same realm still differ in line weight.
      A raises the floor. It does not raise the ceiling.</div>
  </section>

  <section class="sec" style="--hue:var(--gold)">
    <h2><span class="h">乙</span> B · 幕 The Scene</h2>
    <p class="t"><span class="pill">days</span> <b>Every screen becomes a place that reads
      the save.</b> Six drawings in this game already do it: the tower has as many tiers
      as you have seals, the arena is the beast's own realm. This asks what the other
      screens would look like if they did the same. A band of the realm's own sky over
      狩 the hunt. A cave mouth over 洞天. The tower's silhouette over 塔. All of it is
      the scenery that already exists, cropped and reused.</p>
    <div class="two">
      <div class="box"><span class="lab">Now</span>
        <div class="scr"><div class="body">
          <p class="lab" style="margin-bottom:8px">狩 Hunt</p>
          ${three.map((b) => `<div class="beast" style="--hue:${six.colour}">
            <span class="s" style="color:${six.colour}">${icon(b.icon, 34)}</span>
            <span><b>${b.han}</b><i>${b.name}</i></span><em>98%</em></div>`).join('')}
        </div></div>
      </div>
      <div class="box"><span class="lab">With the realm behind it</span>
        <div class="scr">
          <div class="top">${band(6)}<span class="ttl cjk">狩</span></div>
          <div class="body">
          ${three.map((b, i) => `<div class="beast" style="--hue:${six.colour}">
            <span class="s">${sealed(b.icon, six.colour, i === 2 ? 2 : 1, 40)}</span>
            <span><b>${b.han}</b><i>${b.name}</i></span><em>98%</em></div>`).join('')}
        </div></div>
      </div>
    </div>
    <h3>流 And the motion, which is the other half of B</h3>
    <p class="t">The bar is the thing a player watches for weeks and it does not move.
      One CSS animation over the fill, and the qi runs.</p>
    <div class="box">
      <span class="lab">氣 the bar, with the qi running in it</span>
      ${qiBar(six.colour)}
      ${qiBar(eight.colour)}
    </div>
    <div class="cost">
      <span><b>0 KB</b><i>the scenery is already in the build</i></span>
      <span><b>5 screens</b><i>hunt, cave, trials, gear, path</i></span>
      <span><b>CSS only</b><i>no animation library, see below</i></span>
      <span><b>reduced motion</b><i>every effect has an off switch already</i></span>
    </div>
    <div class="rule"><b>The risk, and how it is paid.</b> A phone is a battery. Every
      effect here is a static SVG plus a CSS transform or opacity, which the compositor
      does without waking the main thread, and the stylesheet already honours
      <code>prefers-reduced-motion</code>. Nothing may animate the layout.</div>
  </section>

  <section class="sec" style="--hue:var(--magenta)">
    <h2><span class="h">丙</span> C · 繪 The Painted Game</h2>
    <p class="t"><span class="pill">weeks</span> <b>Real pictures for the 45 named
      creatures, the 9 realms and the 9 heavens.</b> This is the only one of the three
      that raises the ceiling, and the only one with a real bill. The frames below are
      generated stand-ins for the treatment, not for the picture: what a painted card
      would look like in the game's own dark, with the silhouette standing in for the
      art that is not drawn yet.</p>
    <div class="paints">
      ${painted(wardenOf(6).icon, six.colour, wardenOf(6).name, wardenOf(6).han)}
      ${painted(wardenOf(8).icon, eight.colour, wardenOf(8).name, wardenOf(8).han)}
      ${painted(wardenOf(9).icon, realmOf(9).colour, wardenOf(9).name, wardenOf(9).han)}
    </div>
    <div class="cost">
      <span><b>45 to 63</b><i>pictures to make and keep consistent</i></span>
      <span><b>3 to 7 MB</b><i>at 60 to 150 KB each, on a phone</i></span>
      <span><b>weeks</b><i>whoever draws them, including a model</i></span>
      <span><b>1 rule broken</b><i>a picture cannot read the save</i></span>
    </div>
    <div class="rule"><b>Three ways to actually get them, cheapest first.</b>
      <b style="color:var(--text)">1. Public domain.</b> The Met has 406,000 CC0 images
      including centuries of Chinese ink landscape, free of any restriction, with an API.
      That is realm and heaven backdrops solved for nothing, legally, today.
      <b style="color:var(--text)">2. A generated set</b>, one locked prompt and one seed
      family, which is cheap and fast and where the whole difficulty is consistency:
      forty-five creatures that look like one hand rather than forty-five.
      <b style="color:var(--text)">3. A paid pack or an artist</b>, which is the only one
      that gives a style nobody else has.</div>
    <div class="rule"><b>And the thing C costs that is not money.</b> Every drawing in
      this game is a reading of the save. A painted beast is a picture: it cannot get
      bigger with the realm, it cannot show that you have killed a hundred of them. Paint
      the *things*, keep the *state* drawn, and the two have to be designed to sit in the
      same frame. That frame is proposal A, which is why A comes first whatever else
      happens.</div>
  </section>

  <section class="sec">
    <h2><span class="h">庫</span> What is worth taking off the shelf</h2>
    <p class="t">Checked on the web for this page. Licences matter more than looks here:
      the game is going on a store, so anything with a non-commercial clause is out, and
      anything requiring attribution needs a credits line, which the game already has for
      game-icons.net.</p>
    <table>
      <tr><th>What</th><th>Licence</th><th>Verdict</th><th></th></tr>
      ${pack('game-icons.net', '4,180 game icons, the set already in use', 'CC BY 3.0, commercial, credit required',
        'Keep it. It is the largest set built for games and the game already credits its eight authors. The 120 shipped are 3% of it: another 60 would cost nothing.',
        'https://game-icons.net/')}
      ${pack('The Met Open Access', '406,000 images, centuries of Chinese ink painting', 'CC0, no restriction at all',
        'The single best find for C. Real Song and Ming landscape, free, with an API. Backdrops for the nine realms and the nine heavens, out of the actual tradition the game is set in.',
        'https://www.metmuseum.org/hubs/open-access')}
      ${pack('LXGW WenKai', 'a brush-styled CJK typeface', 'SIL OFL 1.1, commercial, embeddable',
        'Worth trying for 漢字 the characters on the title and the realm names. The game is on Noto Serif SC today, which is correct and a little plain.',
        'https://github.com/lxgw/LxgwWenKai')}
      ${pack('Google Fonts CJK', 'Ma Shan Zheng, ZCOOL XiaoWei and the rest', 'mostly OFL, check the specimen page',
        'One display face for the logo and the realm titles only. Never for body text: a CJK face is megabytes, and the game loads two already.',
        'https://fonts.google.com/?subset=chinese-simplified')}
      ${pack('itch.io and OpenGameArt', 'thousands of CC0 and CC BY packs', 'per asset, filter by licence',
        'Mostly pixel art, which is a different game from this one. Worth a search for ink and brush textures rather than for creatures.',
        'https://opengameart.org/')}
      ${pack('CraftPix free section', 'fantasy icon and GUI packs', 'free section is commercial with credit',
        'Their free GUI frames are usable and their style is warmer than this game. A source for frames if A is ever done by hand rather than generated.',
        'https://craftpix.net/categorys/free-icons-for-games/')}
    </table>
    <div class="rule"><b>What not to buy.</b> A second icon set in a different style makes
      the mismatch worse, not better: 115 icons by eight authors already do not agree, and
      the fix for that is one frame around all of them, not more icons.</div>
  </section>

  <section class="sec">
    <h2><span class="h">動</span> Motion, and what it should cost</h2>
    <p class="t">The game has almost none: a few CSS transitions, one clash animation and
      the aura's breathing. Here is what is worth adding, in order of what a player sees
      per minute.</p>
    <table>
      <tr><th>Effect</th><th>Where</th><th>How</th></tr>
      <tr><td><b>氣 The qi running in the bar</b></td><td>Every screen, all day</td>
        <td>One CSS gradient sweep over the fill. 6 lines, no script.</td></tr>
      <tr><td><b>階 A rung opening</b></td><td>The moment the climb happens</td>
        <td>A ring that expands and fades from the bar. The sound and the flag already
          exist; this is the picture of it.</td></tr>
      <tr><td><b>擊 The blow landing</b></td><td>Every fight</td>
        <td>A white flash on the struck figure plus a 4px shake. Transform and opacity
          only, so the compositor does it.</td></tr>
      <tr><td><b>落 A drop arriving</b></td><td>Hunting, which is the loop</td>
        <td>The rank's colour sweeping once across the new tile. It is the one moment
          gear is looked at.</td></tr>
      <tr><td><b>塵 Motes in the air</b></td><td>The arena and the secret rooms</td>
        <td>Already drawn, and static. Ten of them drifting on a CSS keyframe with
          different delays costs nothing.</td></tr>
      <tr><td><b>突破 The breakthrough</b></td><td>Nine times a run</td>
        <td>The one place a heavy effect is earned. The aura blooming outward and the
          colour walking to the next realm over a second and a half.</td></tr>
    </table>
    <div class="rule"><b>And the library question, answered honestly: none of it.</b>
      GSAP is free now and Motion is MIT and anime.js is 6 KB, and this game needs none of
      them. Every effect above is a transform, an opacity or an SVG that is already being
      drawn. The game ships 105 KB of JavaScript today and runs a tick every fifth of a
      second on a phone that is meant to be in a pocket. If one thing ever does need a
      timeline, the Web Animations API is in the browser already.</div>
  </section>

  <section class="sec">
    <h2><span class="h">擇</span> What I would actually do</h2>
    <div class="rule" style="--hue:var(--cyan)"><b>A now.</b> It is hours, it costs
      nothing, it covers ${BEASTS.length} beasts and ${GEAR.length} pieces of gear at
      once, and it makes the mismatch between eight authors stop mattering. Start with
      對 the beast in the arena, because that is the screen the asymmetry is worst on.</div>
    <div class="rule" style="--hue:var(--gold)"><b>B next, in pieces.</b> The band over
      狩 the hunt and the qi running in the bar are an afternoon each and they are the two
      most looked at surfaces in the game.</div>
    <div class="rule" style="--hue:var(--magenta)"><b>C only for a launch push, and start
      with the free half.</b> The Met's CC0 landscape gives the nine realms and the nine
      heavens a real backdrop for nothing. The 45 creatures are the expensive half and
      they can wait until there is a reason to spend.</div>
  </section>

  <section class="sec">
    <h2><span class="h">標</span> The logo, and prompts that will actually get one</h2>
    <p class="t">The icon on the phone today is 打坐 the meditation silhouette from the
      same borrowed library, on a magenta wash. It is honest and it is not a logo: it says
      nothing that a hundred other meditation apps do not say, and it has no wordmark.</p>

    <h3>先 What it has to survive, before any prompt is written</h3>
    <table>
      <tr><th>Where</th><th>What that demands</th></tr>
      <tr><td><b>A home screen, 48 pixels</b></td>
        <td>One shape, readable at a glance. Anything with more than three elements turns
          to mud, and a thin stroke disappears.</td></tr>
      <tr><td><b>Google Play, 512 by 512</b></td>
        <td>PNG, 32 bit, and <b>no transparency</b>. The store icon is a flat square that
          the store rounds itself.</td></tr>
      <tr><td><b>An Android adaptive icon</b></td>
        <td>108 by 108 dp in two layers, foreground and background, and only the inner
          66 dp is guaranteed to survive the mask. Every manufacturer crops a different
          shape, so the mark has to sit inside that circle with room to spare.</td></tr>
      <tr><td><b>Android 13 themed icons</b></td>
        <td>A third layer, monochrome, tinted by the wallpaper. If the mark only works in
          the cyan to magenta ramp, this is where it falls apart.</td></tr>
      <tr><td><b>The game's own dark</b></td>
        <td>Everything in 九境 sits on <code>#080A18</code>. A logo designed on white and
          dropped in will glow wrongly.</td></tr>
    </table>

    <h3>字 The one thing to get out of the way first</h3>
    <div class="rule"><b>Do not ask an image model for the 漢字.</b> DALL·E can place
      Latin letters well enough to iterate on, and it cannot be trusted with 九境: it
      produces characters that are nearly right, which is worse than wrong, and neither
      of us can see it. So generate <b>the mark alone</b>, and set the characters in the
      game's own typeface afterwards, which is a five minute job in any vector editor and
      gives type that is correct, crisp at any size and identical to the game. Ask for the
      Latin wordmark only if you want a lockup to iterate on, and expect to redo it by
      hand.</div>

    <h3>甲 Prompt one: the nine rings</h3>
    <p class="t">The game is nine realms and nine rungs in each. Nine is the shape.</p>
    <pre>A minimalist app icon for a dark Chinese cultivation game.
A single seated meditating figure in clean white silhouette, seen from
the front, centred, small. Around it, nine concentric thin rings,
perfectly circular, each ring slightly brighter than the last, going
from deep cyan (#5FDCFF) at the outside to hot magenta (#FF5FC8) at the
inside. Flat vector illustration, no photorealism, no texture, no
shadows, no bevels. Background: a very dark navy void (#080A18) with a
soft radial glow behind the figure only. Bold, high contrast, readable
at very small sizes. Perfectly symmetrical. Generous empty margin all
around the artwork. Square 1:1, no text, no letters, no characters.</pre>

    <h3>乙 Prompt two: the seal</h3>
    <p class="t">A 印 seal is what the whole art direction is already reaching for, and a
      seal is a logo by construction: a shape inside a border, meant to be small.</p>
    <pre>A minimalist app icon in the style of a traditional Chinese seal stamp,
redrawn for a dark sci-fi cultivation game. A thick rounded-square seal
border, inside it a single stylised mountain of nine ascending peaks,
and one thin vertical line of qi rising from the tallest peak and
breaking the top of the border. Drawn in luminous cyan (#5FDCFF)
turning to magenta (#FF5FC8) toward the top. Flat vector, thick even
strokes, no gradients inside the strokes, no texture, no shadow.
Background: near-black navy (#080A18). Strong silhouette, works at 24
pixels, perfectly centred with wide margins. Square 1:1, no text.</pre>

    <h3>丙 Prompt three: the ascent</h3>
    <p class="t">The one image the whole game is about: a figure sitting still while
      something rises off them for ninety days.</p>
    <pre>App icon for an idle cultivation game. A seated figure in white
silhouette at the bottom centre, and rising from it a single vertical
stream of light that widens into nine soft horizontal bands, like nine
heavens stacked above. The bands run cyan (#5FDCFF) at the bottom
through violet to magenta (#FF5FC8) at the top. Flat vector, minimal,
no faces, no detail on the figure. Dark navy background (#080A18) with
a faint radial glow at the base. Extremely simple, bold, symmetrical,
large empty margin. Square 1:1, no text, no lettering.</pre>

    <h3>丁 And the wordmark, if you want to try it anyway</h3>
    <pre>A horizontal logo lockup for a game called NINEFOLD. On the left, a
simple luminous emblem of nine concentric rings around a small seated
meditating figure. On the right, the single word NINEFOLD in a wide,
geometric, uppercase sans-serif with generous letter spacing, in soft
white. Flat vector, dark navy background (#080A18), cyan to magenta
accent (#5FDCFF to #FF5FC8). No other text, no tagline, no Chinese
characters. Clean, high contrast, plenty of margin. 16:9.</pre>

    <h3>用 How to use what comes back</h3>
    <table>
      <tr><th>Step</th><th>Why</th></tr>
      <tr><td><b>Generate four, pick by squinting</b></td>
        <td>Blur the image until it is 20 pixels wide. Whatever is still recognisable is
          the logo. Everything else was decoration.</td></tr>
      <tr><td><b>Ask for the same thing again, simpler</b></td>
        <td>The single most useful follow-up is <i>same composition, fewer elements,
          thicker strokes, more empty margin</i>. Image models over-decorate by default
          and they subtract well when asked.</td></tr>
      <tr><td><b>Redraw it as vector</b></td>
        <td>What comes back is a raster picture of a logo. Trace it, or rebuild it from
          circles and paths: this game draws everything as SVG and the icon should be a
          file you can recolour, not a JPEG of an idea.</td></tr>
      <tr><td><b>Set the 漢字 yourself</b></td>
        <td>九境 in the game's own face, which is Noto Serif SC today. A brush face like
          LXGW WenKai under the OFL is worth a look for the title only.</td></tr>
      <tr><td><b>Export the four files the platforms want</b></td>
        <td><code>public/icon-192.png</code> and <code>icon-512.png</code> for the web
          manifest, which the game already ships and which the maskable entry already
          points at. Then the adaptive pair for the APK, foreground and background, plus
          a white-on-transparent monochrome for themed icons.</td></tr>
      <tr><td><b>Test it on a busy wallpaper</b></td>
        <td>An adaptive icon gets cropped to a circle on one phone and a squircle on
          another, and a themed one gets recoloured entirely. If the mark only reads in
          its own two colours, it is not finished.</td></tr>
    </table>
    <div class="rule"><b>One more thing worth saying out loud.</b> A logo made by a model
      is fine for a game of this size, and the risk is not quality, it is
      <b>sameness</b>: the same prompt vocabulary produces the same glowing-circle icon
      everybody else on the store has. The way out is to take the shape from the game
      rather than from the genre, and the game's own shape is the ladder: nine of
      something, always nine.</div>
  </section>

  <footer class="sec" style="color:var(--faint);font-size:13.5px">
    <p>Written by <code>npm run artprops</code>. The drawings are generated from the
      game's own tables and its own icon set. Icons from game-icons.net under CC BY 3.0.</p>
  </footer>
</div>
`;

const lifted = liftArt(page, 'prop-plates');
writeFileSync('art-proposals.html', lifted.page);
const kb = Math.round(writePlates('prop-plates', lifted.plates) / 1024);
console.log(`art-proposals.html · ${Math.round(lifted.page.length / 1024)} KB · `
  + `${lifted.plates.size} drawings · ${kb} KB beside it`);
